package dev.sakashita.tateyokopdf.tools;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import dev.sakashita.tateyokopdf.domain.model.ReadingDirection;
import dev.sakashita.tateyokopdf.web.job.ProgressEvent;
import java.lang.reflect.RecordComponent;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generates {@code frontend/src/lib/types.ts} from the sealed {@link ProgressEvent} hierarchy and
 * the {@link ReadingDirection} enum.
 *
 * <p>The output is the source of truth for the WebSocket / HTTP wire contract. Running this from
 * the Gradle {@code generateApiTypes} task means a developer cannot rename a field on the Java side
 * and forget to update the frontend type — the next {@code just check} run will fail the diff
 * guard.
 *
 * <p>Implementation note: we walk the sealed hierarchy via reflection rather than route the schema
 * through Jackson → jsonschema-generator → quicktype. The simpler path requires no extra
 * dependencies and produces output that exactly matches the frontend's pre-existing handwritten
 * shape, so consumer code in {@code +page.svelte} does not need to change.
 */
public final class ApiTypesGenerator {

  private ApiTypesGenerator() {}

  public static void main(String[] args) throws Exception {
    if (args.length != 1) {
      System.err.println("Usage: ApiTypesGenerator <output-path>");
      System.exit(64);
    }
    Path target = Path.of(args[0]);
    String body = render();
    Path parent = target.toAbsolutePath().getParent();
    if (parent != null) {
      Files.createDirectories(parent);
    }
    Files.writeString(target, body);
    System.out.println("Wrote " + target);
  }

  static String render() {
    // Enums referenced from any record component are collected and emitted as named unions so
    // the generated file stays self-contained.
    Map<String, Class<? extends Enum<?>>> enumsToEmit = new LinkedHashMap<>();
    String sealedUnion = renderSealedUnion(ProgressEvent.class, enumsToEmit);
    enumsToEmit.putIfAbsent(ReadingDirection.class.getSimpleName(), ReadingDirection.class);

    StringBuilder out = new StringBuilder();
    out.append("// DO NOT EDIT — generated by ./gradlew generateApiTypes\n");
    out.append("// Source: dev.sakashita.tateyokopdf.web.job.ProgressEvent\n");
    out.append("//         dev.sakashita.tateyokopdf.domain.model.ReadingDirection\n");
    out.append("\n");
    out.append(sealedUnion);
    out.append("\n");
    out.append("export type SubmitResponse = { id: string };\n");
    for (Class<? extends Enum<?>> e : enumsToEmit.values()) {
      out.append("\n").append(renderEnumUnion(e));
    }
    return out.toString();
  }

  private static String renderSealedUnion(
      Class<?> sealed, Map<String, Class<? extends Enum<?>>> enumsToEmit) {
    if (!sealed.isSealed()) {
      throw new IllegalArgumentException(sealed + " is not sealed");
    }
    JsonTypeInfo typeInfo = sealed.getAnnotation(JsonTypeInfo.class);
    JsonSubTypes subTypes = sealed.getAnnotation(JsonSubTypes.class);
    if (typeInfo == null || subTypes == null) {
      throw new IllegalArgumentException(
          sealed + " must be annotated with @JsonTypeInfo + @JsonSubTypes");
    }
    String discriminatorProp = typeInfo.property();
    StringBuilder out = new StringBuilder();
    out.append("export type ").append(sealed.getSimpleName()).append(" =\n");
    JsonSubTypes.Type[] entries = subTypes.value();
    for (int i = 0; i < entries.length; i++) {
      JsonSubTypes.Type entry = entries[i];
      Class<?> variant = entry.value();
      String tag = entry.name();
      out.append("\t| ");
      out.append("{ ").append(discriminatorProp).append(": '").append(tag).append("'");
      for (RecordComponent c : variant.getRecordComponents()) {
        out.append("; ")
            .append(c.getName())
            .append(": ")
            .append(tsTypeFor(c.getType(), enumsToEmit));
      }
      out.append(" }");
      out.append(i == entries.length - 1 ? ";\n" : "\n");
    }
    return out.toString();
  }

  private static String renderEnumUnion(Class<? extends Enum<?>> enumType) {
    Enum<?>[] constants = enumType.getEnumConstants();
    List<String> quoted = new ArrayList<>(constants.length);
    for (Enum<?> c : constants) {
      quoted.add("'" + c.name() + "'");
    }
    // Single-line for <=2 constants (keeps trivial enums compact); otherwise multi-line so the
    // Biome formatter accepts the file without complaint.
    if (quoted.size() <= 2) {
      return "export type " + enumType.getSimpleName() + " = " + String.join(" | ", quoted) + ";\n";
    }
    StringBuilder out = new StringBuilder();
    out.append("export type ").append(enumType.getSimpleName()).append(" =\n");
    for (int i = 0; i < quoted.size(); i++) {
      out.append("\t| ").append(quoted.get(i));
      out.append(i == quoted.size() - 1 ? ";\n" : "\n");
    }
    return out.toString();
  }

  @SuppressWarnings("unchecked")
  private static String tsTypeFor(
      Class<?> javaType, Map<String, Class<? extends Enum<?>>> enumsToEmit) {
    if (javaType == int.class || javaType == Integer.class) {
      return "number";
    }
    if (javaType == long.class || javaType == Long.class) {
      return "number";
    }
    if (javaType == double.class
        || javaType == Double.class
        || javaType == float.class
        || javaType == Float.class) {
      return "number";
    }
    if (javaType == boolean.class || javaType == Boolean.class) {
      return "boolean";
    }
    if (javaType == String.class) {
      return "string";
    }
    if (javaType.isEnum()) {
      enumsToEmit.putIfAbsent(javaType.getSimpleName(), (Class<? extends Enum<?>>) javaType);
      return javaType.getSimpleName();
    }
    throw new IllegalArgumentException("No TS mapping for " + javaType);
  }
}
