// DO NOT EDIT — generated by ./gradlew generateApiTypes
// Source: dev.sakashita.tateyokopdf.web.job.ProgressEvent
//         dev.sakashita.tateyokopdf.domain.model.ReadingDirection

export type ProgressEvent =
	| { type: 'started'; total: number; traceId: string }
	| { type: 'progress'; current: number; total: number; traceId: string }
	| { type: 'completed'; traceId: string }
	| { type: 'failed'; errorKind: ErrorKind; message: string; traceId: string };

export type SubmitResponse = { id: string };

export type ErrorKind =
	| 'PDF_CORRUPTED'
	| 'PDF_PASSWORD_PROTECTED'
	| 'PDF_TOO_LARGE'
	| 'PDF_NOT_FOUND'
	| 'PDF_INVALID_PAGE'
	| 'PDF_WRITE_FAILED'
	| 'UPLOAD_INVALID'
	| 'UPLOAD_EMPTY'
	| 'JOB_NOT_FOUND'
	| 'JOB_EXPIRED'
	| 'JOB_OUTPUT_GONE'
	| 'INVALID_PARAMETER'
	| 'OUT_OF_MEMORY'
	| 'INTERNAL';

export type ReadingDirection = 'RTL' | 'LTR';
